# .github/workflows/ci.yml

name: Node.js CI

on:
  push:
    branches:
      - main
      - feat/server
  pull_request:
    branches:
      - main
      - feat/server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # You can specify your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test